name: ultimate_cloud
description: "Yeap"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
#  media_kit: ^1.1.11
#  media_kit_video: ^1.2.5
#  media_kit_libs_video: ^1.0.5
#  media_kit_libs_macos_video: ^1.1.4

  cupertino_icons: ^1.0.8
  flutter_vlc_player_16kb: ^7.4.4
  file_picker: ^10.0.0
  flutter_speed_dial: ^7.0.0
  http: ^1.2.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  config:
    enable-swift-package-manager: false
  uses-material-design: true

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter.ttf
          style: normal